### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SquirrelAssassin** [azureautomation/azure-automation-ise-addon#115]
We moved items in azure, now when I launch the plugin I see "Object reference not set to an instance of an object"
If you uninstall the module and reinstall, the configuration is still there.  How do you re-install this as if fresh?  
Where is the configuration information stored?

**Comment by JAL9302** [comment]
There should be a file at C:<username>\AzureAutomationAuthoringToolkitConfig.json. Can you try renaming it to something like AzureAutomationAuthoringToolkitConfig-old.json so the file appears deleted to the ISE add on and then try installing again?

Nice username, by the way.

**Comment by JakobGSvendsen** [comment]
I have the same error. but it only happens on one of my 4 automation accounts. I tried to delete the file above but no luck.

I can add that this account was created using Classic a long time ago. The others that works are created via ARM. (unfortunately this is my main account with everything in it). As a troubleshooting attempt I tried to move the account to another resource group in ARM which did not have a super long name as the old classic ones, but no luck.
I have also tried to open code and attach debugger but It does not seem to allowe breakpoints.

![image](https://cloud.githubusercontent.com/assets/3460807/17622380/4aad3630-609a-11e6-80cf-135a4b697a22.png)

I have now narroed it down to beeing part of the DSC code, as I changed the error message and got this stack trace:

![image](https://cloud.githubusercontent.com/assets/3460807/17623373/06041aac-60a0-11e6-8bc6-d3dcc3074225.png)

Then I skipped the DSC code and compiled a new version and everything works (except DSC ofc).

This account has been in DSC preview since day 1, so I tried to cleanup all configs and nodes, but no luck.

**Comment by eamonoreilly** [comment]
Hi Jakob - is this using the latest source code from GitHub? I had a made a few changes recently to catch some exceptions. If this is happening on the latest code, I'll have a look and see how to fix. 
Thanks,
Eamon

**Comment by JakobGSvendsen** [comment]
Hello Eamon!

I was using the newest code from this repo which I compiled and ran. and It is also the same in the version on powershellgallery.com

**Comment by JakobGSvendsen** [comment]
just to be clear, if I disable the DSC part, it works. I changed this 

 /\* Update Configurations */
                  beginBackgroundWork("Getting configuration data for " + account.Name);
                      if (DSCListViewModel != null) DSCListViewModel.Clear();
                      if (assetListViewModel != null) assetListViewModel.Clear();
                      DSCListViewModel = new ObservableCollection<AutomationDSC>(await AutomationDSCManager.GetAllConfigurationMetadata(iseClient.automationManagementClient,
                            iseClient.currWorkspace, iseClient.accountResourceGroups[iseClient.currAccount].Name, iseClient.currAccount.Name, localScripts));
                      endBackgroundWork("Done getting configuration data");

to 

   beginBackgroundWork("Getting configuration data for " + account.Name);
                    if (DSCListViewModel != null) DSCListViewModel.Clear();
                    if (assetListViewModel != null) assetListViewModel.Clear();
                    DSCListViewModel = new ObservableCollection<AutomationDSC>();
                    endBackgroundWork("Done getting configuration data");

just to have some empty lists to be able to use the plugin

**Comment by JakobGSvendsen** [comment]
I am still having this issue. I might be connected to another isssue, that I have DSC configs that I cannot delete

PS C:\Users\JGS\OneDrive\Privat\FTP\FlashFXP> Get-AzureRmAutomationDscConfiguration -ResourceGroupName $a.ResourceGroupName -AutomationAccountName $a.AutomationAccountName

ResourceGroupName     : Automation
AutomationAccountName : CoretechAutomation
Location              : West Europe
State                 : Published
Name                  : Demo
Tags                  : {}
CreationTime          : 19-06-2015 11:09:38 +02:00
LastModifiedTime      : 19-06-2015 14:37:51 +02:00
Description           : 
Parameters            : {}
LogVerbose            : False

ResourceGroupName     : Automation
AutomationAccountName : CoretechAutomation
Location              : West Europe
State                 : Published
Name                  : PSUG
Tags                  : {}
CreationTime          : 22-06-2015 14:15:33 +02:00
LastModifiedTime      : 22-06-2015 14:36:12 +02:00
Description           : 
Parameters            : {}
LogVerbose            : False

PS C:\Users\JGS\OneDrive\Privat\FTP\FlashFXP> Get-AzureRmAutomationDscConfiguration -ResourceGroupName $a.ResourceGroupName -AutomationAccountName $a.AutomationAccountName | Remove-AzureRmAutomationDscConfiguration -force
Remove-AzureRmAutomationDscConfiguration : The Dsc Configuration was not found. Configuration name Demo.
At line:1 char:129
- ... tomationAccountName | Remove-AzureRmAutomationDscConfiguration -force
-                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Remove-AzureRmAutomationDscConfiguration], ResourceNotFoundException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RemoveAzureAutomationDscConfiguration

Remove-AzureRmAutomationDscConfiguration : The Dsc Configuration was not found. Configuration name PSUG.
At line:1 char:129
- ... tomationAccountName | Remove-AzureRmAutomationDscConfiguration -force
-                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Remove-AzureRmAutomationDscConfiguration], ResourceNotFoundException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RemoveAzureAutomationDscConfiguration

**Comment by JakobGSvendsen** [comment]
This bug was caused by an abnormality in my account. I had 2 very old DSC configs (from very early preview) which had some issues. they couldnt be deleted from either PS or portal. Autoation engineers helped me delete them manyally for me. And now everything works as a charm!
 you can close/delete this now, as I probably was the only one who has experienced it! 
have a great ignite!
Thanks! :)

**Comment by eamonoreilly** [comment]
Thanks Jakob - great to hear.
