### ISSUE TITLE
Get-AutomationPSCredential returns incorrect password when '£' character is present.

### ISSUE THREAD

**Issue by ChrisA87** [azureautomation/azure-automation-ise-addon#135]
Ran a test on my local machine and it failed to get the correct password. All '£' characters were replaced with '�' .

This didn't seem to be an issue when I ran the runbook on my automation account.

**Comment by eamonoreilly** [comment]
Thanks Chris for raising this issue. I believe it is fixed with the above commit and should show up in the next release of the add-on. If you need the fix now, you could build the project and use the generated dll and update the assets module.
I'll close the issue now but please reopen if this is not addressed in the next release.
Thanks,
Eamon
