### ISSUE TITLE
"Launching login window User cancelled sign in"

### ISSUE THREAD

**Issue by JakobGSvendsen** [azureautomation/azure-automation-ise-addon#23]
using the version 0.1.5 

 No matter if I try to logon with microsoft account or domain account I get the same msg:

"Launching login window User cancelled sign in"

Any suggestions?

If not, I will check out the code to try to fix it myself, I really want to show this next week ;-)

**Comment by JakobGSvendsen** [comment]
Already found the issue

I had left the example email in the textbox in the addon control it self.
![image](https://cloud.githubusercontent.com/assets/3460807/9364473/d5956f50-46ac-11e5-885f-7fe716d10378.png)

when I changed the textbox to the same account as a Logged in as (jgs@coretech.dk) and used the sign in buttons afterwards, it worked as expected.

Seems to be a little counter intuitive imho.

**Comment by JAL9302** [comment]
Should we just not have an example email in there? Would that help? If so we should reopen as there's a fix we can do to make things slightly easier

**Comment by JakobGSvendsen** [comment]
I dont think it will help.
I mean .. it seems weird that it does not change automatically when using a specific logon account in the popup logon window.

Wouldnt it be possible to not have to write the email both in the textbox from my pic and in the logon popup window?

Of cause If I change it first, then popup window will open as the correct email. but if I dont, the error will be "user cancelled".

Maybe if the textbox is empty from start, or with some example email, but the sign in button is grayed/disabled  until the textbox is changed.

**Comment by Stijnc** [comment]
is there a real benefit of having the email text field? First logon experience prompt for email and password, store the email somewhere not visible and on subsequent logons the entry should be the following screen instead of a prefilled account?
![logon ise](https://cloud.githubusercontent.com/assets/1662677/9369041/10bf88ee-46c7-11e5-8703-f68f2146ba22.PNG)

**Comment by eamonoreilly** [comment]
I removed the default text when initially launched. This was left over from earlier builds when we only supported Azure AD authentication and wanted to give some hints to the user on the format to enter.
We now support Microsoft accounts also so this is not required. With it blank, it will ask you to give your email address and then direct to the right login page (Work or Microsoft account) depending on the email you enter.

The reason I kept the email box there is that it helps the user know who they are logged in as and also to make it easier to log in for future sessions since you would not need to type your email address in.

Hopefully this might remove some of the confusion for first time usage but let me know if there are still additional issues and figure out what we can do.
Thanks guys.
