### ISSUE TITLE
Bugbash: Confused about runbooks workflow

### ISSUE THREAD

**Issue by rebro-msft** [azureautomation/azure-automation-ise-addon#52]
I had a runbook, and downloaded it locally.  I opened it to see what is inside it, but I didn't change anything.  I wanted to run it in Azure, but that button was greyed out.  It was unclear to me (someone else had to explain to me) that I needed to Upload Draft (I hadn't changed anything) before the Test Draft in Azure button became available.  It would be nice to have a clear indication of the proper workflow.

**Comment by eamonoreilly** [comment]
Thanks Rebecca - I think Alex can sync with you and see if we can streamline this a little bit or perhaps have some help content on the expected flow.

**Comment by robplank** [comment]
@eamonoreilly,
You can have @alstab also reach out to me I have a few comments/ideas on this.

**Comment by alstab** [comment]
Rebecca encountered a couple of issues here:
1. Having downloaded the runbook, the "test on Azure" button should not have been greyed out. This has been fixed in a recent commit.
2. The overall workflow was not clear. 

In light of (1), I am closing this issue.

(2) is also a real issue, but I will track it separately. I will follow up with Rob and Rebecca at some point about possible solutions.
