### ISSUE TITLE
Don't use root of system drive as default working path

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#55]
Use a path in the user profile instead. 

![image](https://cloud.githubusercontent.com/assets/466713/9963564/0a3d69da-5de9-11e5-81b0-f9eb3e901324.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by eamonoreilly** [comment]
The path is already so long that I think it is easier to manage if the user picks something closer to the root path. I think this is a preference depending on the user so I'll see if we get additional feedback but I'm inclined to leave it as is for now since users can select a different path if they wish to.

**Comment by eamonoreilly** [comment]
Changed to user userprofile. Should show up in the next official build
