### ISSUE TITLE
ISE Add-on & Azure PS Module - share authentication

### ISSUE THREAD

**Issue by DexterPOSH** [azureautomation/azure-automation-ise-addon#64]
At the moment, One needs to authenticate to the Azure Automation ISE Add-on and Azure PowerShell module separately.
It would be nice to have them share the auth details, If I login to one the other should use the same authentication context.

![2setofauth](https://cloud.githubusercontent.com/assets/6275375/10414995/32401108-7004-11e5-9acb-5ae26aeeecc0.PNG)

**Comment by eamonoreilly** [comment]
Thanks Dexter, unfortunately, non Microsoft work accounts (example hotmail, yahoo, gmail) can not be used for non interactive authentication against Azure that Azure Automation requires since it needs authentication at runtime. 
If you log in with a work account, it would be possible to automatically create a credential asset for you that you could then use in your runbook with the Add-Azure account.
Thanks for the feedback - we really appreciate it.
Eamon

**Comment by eamonoreilly** [comment]
We now have Azure Automation RunAs accounts (Service principal authentication) so I have integrated the ISE Add-On with these credentials so that the PowerShell console will use this RunAs account for the automation account selected.
Closing out this item with this integration as I think it accomplishes what you suggested. Thanks again for the feedback.
Eamon
