### ISSUE TITLE
Test job output window enhancements

### ISSUE THREAD

**Issue by NoahStahl** [azureautomation/azure-automation-ise-addon#92]
A few ideas/requests related to the test job output window:
- Configurable or more frequent refresh. The hard-coded 30 second frequency isn't that useful and just leads to lots of refresh button clicking for the impatient among us :).
- Streaming behavior. I like the portal behavior to show the output streaming out as it is produced, rather than the entire window contents being cleared and reset.
- Disable "Stop Job" button when a job isn't running

**Comment by eamonoreilly** [comment]
Thanks Noah. Removed the refresh button and made the polling 5 seconds as hopefully this feels real time like the portal. The following changes were made:

1) Polling is now 5 seconds and configurable in AutomationISE.dll.config
2) Output now streams to the window instead of full refresh
3) Stop job should now be disabled when job is not running
4) Output window automatically scrolls to the bottom of the window during streaming of output

**Comment by NoahStahl** [comment]
Awesome, this will be a nice improvement! Thanks Eamon.
